#+title: Samb's Doom Emacs Config
#+author: Samb

* 基础行为 & 变量
** Server
#+begin_src emacs-lisp
  (server-start)
#+end_src

** 你的名字
#+begin_src emacs-lisp
  (setq user-full-name "Jie Samb"
        user-mail-address "samb233@hotmail.com")
#+end_src

** 文件编码
将文件编码全部设定为utf-8-unix
#+begin_src emacs-lisp
  (setq-default buffer-file-coding-system 'utf-8-unix)
  (set-default-coding-systems 'utf-8-unix)
  (prefer-coding-system 'utf-8-unix)
#+end_src

** 窗口大小 & 名称
设置窗口的大小。
我喜欢用较小的窗口记笔记，所以设置的80列50行。写代码是最大化窗口即可。
#+begin_src emacs-lisp
  (pushnew! default-frame-alist '(width . 80) '(height . 50))
  ;; (add-to-list 'default-frame-alist '(fullscreen . maximized))
#+end_src

设置窗口透明度。
设置alpha是调用系统窗口混合器来实现半透明，文字和图片也会半透明化
而alpha-background是emacs29新引入的特性，只半透明背景，不会半透明文字和图片。
#+begin_src emacs-lisp
  ;; (add-to-list 'default-frame-alist '(alpha-background . 95))
  ;; (add-to-list 'default-frame-alist (cons 'alpha 90))
#+end_src

设置标题栏名称。
我将其设置为文件路径。
#+begin_src emacs-lisp
  (setq frame-title-format
        '((:eval (if (buffer-file-name)
                     (abbreviate-file-name (buffer-file-name))
                   "%b"))))
#+end_src

** 相对行号。
使用evil-mode怎么能少了这个！
#+begin_src emacs-lisp
  (setq display-line-numbers-type 'relative)
#+end_src

* 基础外观
** 字体
设置字体与字体大小。
将doom-unicode-font设置为Sarasa Mono SC即可解决Doom Emacs的中文显示问题。
Sarasa这个字体能在一定程度上与英文对齐，能让代码的80线不再歪歪扭扭。
并且能兼容Doom的Big Mode。
#+begin_src emacs-lisp
  (setq doom-font (font-spec :family "Iosevka Medium" :size 13.0))
  ;; (setq doom-variable-pitch-font (font-spec :family "Noto Serif CJK SC"))
  (setq doom-unicode-font (font-spec :family "Sarasa Mono SC" ))
#+end_src

** 主题
#+begin_src emacs-lisp
  (setq doom-theme 'doom-tomorrow-day)
#+end_src

** doom-modeline
简洁一点，去掉部分图标
#+begin_src emacs-lisp
  (setq doom-modeline-modal t)
  (setq doom-modeline-modal-icon nil)
  (setq doom-modeline-buffer-encoding t)
  (setq doom-modeline-vcs-max-length 20)
  (setq doom-modeline-height 28)
  (setq doom-modeline-buffer-modification-icon nil)
  (setq doom-modeline-buffer-state-icon nil)
  (after! doom-modeline
    (set-face-attribute 'mode-line-active nil :background "#f4f4f4")
    (setq doom-modeline-buffer-file-name-style 'buffer-name)
    )
#+end_src

设置buffer name重复时的处理。
在前面添加路径
doom里需要注意和persp-mode的冲突: https://github.com/doomemacs/doomemacs/issues/6205
#+begin_src emacs-lisp
  (after! persp-mode
    (setq-hook! 'persp-mode-hook uniquify-buffer-name-style 'forward)
    )
#+end_src

** indent-guide
设置indent-guide的样式
#+begin_src emacs-lisp
  (setq highlight-indent-guides-method 'bitmap)
  (setq highlight-indent-guides-responsive 'top)
#+end_src

** 各类popup
设置错误弹窗为popup
#+begin_src emacs-lisp
  (set-popup-rule! "^\\*format-all-errors*" :size 0.3 :modeline t :quit t)
#+end_src

* 基础按键
设置鼠标滚动。
#+begin_src emacs-lisp
  (setq scroll-margin 9)
  (setq mouse-wheel-scroll-amount '
        (3
         ((shift) . hscroll)
         ((meta))
         ((control) . text-scale)))
  (setq mouse-wheel-progressive-speed nil) ;; don't accelerate scrolling
  (setq mouse-wheel-follow-mouse 't) ;; scroll window under mouse
  (setq scroll-step 1) ;; keyboard scroll one line at a time
#+end_src

emacs29新加入的像素滚动模式。
mac上适配很好，很有用
linux上就一般般，还是不开习惯
#+begin_src emacs-lisp
  ;; (pixel-scroll-precision-mode t)
#+end_src

设置visual模式下Shift-j和Shift-k上下移动代码块
#+begin_src emacs-lisp
  (evil-define-key 'visual 'global
    (kbd "J") 'drag-stuff-down
    (kbd "K") 'drag-stuff-up)
#+end_src

使用consult-line替代I-search
#+begin_src emacs-lisp
  (evil-define-key 'normal 'global (kbd "C-s") 'consult-line)
  (map! "C-s" #'consult-line)
  ;; (setq consult-line-start-from-top t)
#+end_src

设置Ctrl-v和Alt-v粘贴
#+begin_src emacs-lisp
  (map! "C-v" #'yank)
  (map! "M-v" #'yank)
#+end_src

设置Ctrl-z撤销，Ctrl-Z重做
#+begin_src emacs-lisp
  (evil-define-key 'insert 'global (kbd "C-z") 'undo-fu-only-undo)
  (evil-define-key 'normal 'global (kbd "C-z") 'undo-fu-only-undo)
  (evil-define-key 'insert 'global (kbd "C-S-z") 'undo-fu-only-redo)
  (evil-define-key 'normal 'global (kbd "C-S-z") 'undo-fu-only-redo)
#+end_src

设置:q命令只关闭buffer，不关闭emacs，关闭时，输入:quit
#+begin_src emacs-lisp
  (evil-ex-define-cmd "q" 'kill-this-buffer)
  (evil-ex-define-cmd "quit" 'evil-quit)
#+end_src

设置]e [e跳转错误
在doom emacs没有官方支持flymake前的妥协方案
#+begin_src emacs-lisp
  (evil-define-key 'normal 'global (kbd "] e") 'flymake-goto-next-error)
  (evil-define-key 'normal 'global (kbd "[ e") 'flymake-goto-prev-error)
#+end_src

* 基础插件
** undo
默认的undo行为在我看来不能适应。
写代码是undo是不靠谱的这件事，太可怕了。
#+begin_src emacs-lisp
  (setq undo-no-redo t)
  (setq evil-want-fine-undo t)
#+end_src

** recentf
设置recentf最大储存项
doom默认的200个也太少了，至少1000吧
#+begin_src emacs-lisp
  (after! recentf
    (setq recentf-max-saved-items 1000)
    )
#+end_src

** evil
设置各个模式的tags。
会显示在doom-modelien上。
设置成全名，让我有种在vim的熟悉感，非常爽。
#+begin_src emacs-lisp
  (after! evil
    (setq evil-emacs-state-tag "EMACS ")
    (setq evil-insert-state-tag "INSERT")
    (setq evil-motion-state-tag "MOTION")
    (setq evil-normal-state-tag "NORMAL")
    (setq evil-replace-state-tag "REPLACE")
    (setq evil-operator-state-tag "OPERATOR")
    (setq evil-visual-char-tag "VISUAL")
    (setq evil-visual-line-tag "V-LINE")
    (setq evil-visual-block-tag "V-BLOCK")
    (setq evil-visual-screen-line-tag "V-SCREEN")
    )
#+end_src

** magit
设置clone的默认文件夹
#+begin_src emacs-lisp
  (setq magit-clone-default-directory "~/Codes/Lab/")
#+end_src

** vc-state
vc设置，因为性能原因被关闭了。
但随时随地知道git状态其实是蛮重要的，我把它打开。
#+begin_src emacs-lisp
  (setq auto-revert-check-vc-info t)
#+end_src

* 代码补全
我使用eglot+corfu的组合。尽量多的利用emacs已经合并的插件。

** eglot
eglot写golang时，会对已排序好的候选词再进行一次排序
导致实际上变成了乱序。故不用。
设置eglot的一些快捷键
#+begin_src emacs-lisp
  (map! :leader
        (:prefix-map ("l" . "LSP")
         :desc "LSP rename" "n" #'eglot-rename
         :desc "LSP find definitions" "f" #'xref-find-definitions
         :desc "LSP find reference" "r" #'xref-find-references
         :desc "LSP restart workspace" "R" #'eglot-reconnect
         ))
#+end_src

配置eglot。
由于eglot只支持了最基础的lsp协议，有一些协议没有支持
先将其屏蔽，有时间再找实现
屏蔽列表
#+begin_src emacs-lisp
  (after! eglot
    (set-face-attribute 'eglot-highlight-symbol-face nil :background "#d6d4d4")
    (setq eglot-events-buffer-size 0)
    (setq eglot-stay-out-of '(snippet))
    ;; (add-hook 'eglot-managed-mode-hook (lambda () (eglot-inlay-hints-mode -1)))
    (setq eglot-ignored-server-capabilities '(:inlayHintProvider))
    )
#+end_src

** eldoc
设置eldoc buffer为popup
#+begin_src emacs-lisp
  (setq eldoc-echo-area-display-truncation-message nil)
  (setq eldoc-echo-area-use-multiline-p nil)
  (set-popup-rule! "^\\*eldoc*" :size 0.15 :modeline nil :quit t)
#+end_src

** corfu
#+begin_src emacs-lisp
  (after! corfu
    (setq corfu-preselect 'prompt)
    ;; (setq corfu-preview-current nil)
    (setq corfu-auto-prefix 1)
    (setq corfu-auto-delay 0.1)
    (setq cape-dict-file "~/.doom.d/dict/words")
    (map! :map corfu-map
          :i "TAB" #'corfu-next
          :i [tab] #'corfu-next
          :i "S-TAB" #'corfu-previous
          :i [backtab] #'corfu-previous
          :i "C-j" #'corfu-next
          :i "C-k" #'corfu-previous
          :i "C-l" #'corfu-insert-separator
          :i "C-i" #'corfu-info-documentation
          :i "C-g" #'corfu-quit
          )
    (map! :map global-map
          :i "C-S-p" #'cape-file)
    )
#+end_src

并设置在退出insert-state时关闭补全菜单
#+begin_src emacs-lisp
  (add-hook! 'evil-insert-state-exit-hook #'corfu-quit)
#+end_src

并设置corfu使用all-the-icon而不是使用kind-icon。
图标并不好看，而且下载github的图标非常非常耗时间。
#+begin_src emacs-lisp
  (use-package! kind-all-the-icons
    :after corfu
    )

  (after! corfu
    (add-to-list 'corfu-margin-formatters #'kind-all-the-icons-margin-formatter)
    )
#+end_src

** yasnippet
用于在使用lsp-enable-snippet时解决corfu与yas的tab冲突。
#+begin_src emacs-lisp
  ;; (after! yasnippet
  ;;   (defun my-corfu-frame-visible-h ()
  ;;     (and (frame-live-p corfu--frame) (frame-visible-p corfu--frame)))
  ;;   (add-hook 'yas-keymap-disable-hook #'my-corfu-frame-visible-h)
  ;;   )
#+end_src

* 文件管理
** dired
由于我取消勾选了doom的dired模块，所以需要自己设置一些dired的选项。
#+begin_src emacs-lisp
  (use-package! dired
    :commands dired-jump
    :init
    (setq dired-dwim-target t
          dired-hide-details-hide-symlink-targets nil
          dired-recursive-copies  'always
          dired-recursive-deletes 'top
          dired-create-destination-dirs 'ask)
    :config
    (setq dired-omit-files
          (concat "\\`[.][.]?\\'"
                  "\\|^\\.DS_Store\\'"
                  "\\|^\\.project\\(?:ile\\)?\\'"
                  "\\|^\\.\\(?:svn\\|git\\)\\'"
                  "\\|^\\.ccls-cache\\'"
                  "\\|\\(?:\\.js\\)?\\.meta\\'"
                  "\\|\\.\\(?:elc\\|o\\|pyo\\|swp\\|class\\)\\'"))
    (map! :map dired-mode-map :ng "q" #'quit-window)
    )
#+end_src

** dirvish
Dirvish真是接近完美的文件管理器。除了鼠标操作比较难受外，处处让我感到满足。
#+begin_src emacs-lisp
  (use-package! dirvish
    :defer t
    :init (after! dired (dirvish-override-dired-mode))
    :hook (dired-mode . dired-omit-mode)
    :custom
    (dirvish-quick-access-entries ; It's a custom option, `setq' won't work
     '(("h" "~/"                          "Home")
       ("c" "~/Codes/"                    "Codes")
       ("D" "~/Documents/"                "Documents")
       ("w" "~/Works/"                    "Works")
       ("d" "~/Downloads/"                "Downloads")
       ("P" "~/Pictures/"                 "Pictures")
       ("v" "~/Videos/"                   "Videos")
       ("s" "~/Shared/"                   "Shared")
       ("n" "~/Notes/"                    "Notes")
       ("b" "~/Books/"                    "Books")
       ("M" "/mnt/"                       "Drives")
       ("T" "~/.local/share/Trash/files/" "TrashCan")
       ))
    :config
    ;; (dirvish-peek-mode) ; Preview files in minibuffer
    (dirvish-side-follow-mode) ; similar to `treemacs-follow-mode'
    ;; (setq dirvish-reuse-session nil) ; disable session reuse
    ;; (setq dirvish--debouncing-delay 2)
    (setq dirvish-async-listing-threshold 10000)
    (setq dirvish-redisplay-debounce 0.01)
    (setq dirvish-use-mode-line nil)
    ;; (setq dirvish-default-layout '(0 0.4 0.6))
    ;; (setq dirvish-mode-line-format
    ;;       '(:left (sort symlink) :right (omit yank index)))
    (setq dirvish-header-line-height '41)
    ;; (setq dirvish-mode-line-height '46)
    (setq dirvish-attributes
          '(file-time all-the-icons file-size collapse subtree-state vc-state git-msg))
    (setq dirvish-all-the-icons-height 0.9)
    (setq delete-by-moving-to-trash t)
    (setq dired-listing-switches
          "-l --almost-all --human-readable --group-directories-first --no-group --time-style=iso")
    (setq dirvish-fd-default-dir "/home/jiesamb/")
    (setq dirvish-open-with-programs
          `(
            (,dirvish-audio-exts . ("mpv" "%f"))
            (,dirvish-video-exts . ("mpv" "%f"))
            (,dirvish-image-exts . ("eog" "%f"))
            (("doc" "docx") . ("wps" "%f"))
            (("ppt" "pptx") . ("wpp" "%f"))
            (("xls" "xlsx") . ("et" "%f"))
            (("pdf") . ("evince" "%f"))
            (("odt" "ods" "rtf" "odp") . ("libreoffice" "%f"))
            (("epub") . ("koodo-reader" "%f"))
            ))
    (setq dirvish-header-line-format '(:left (path) :right (yank sort index " ")))
    (setq dirvish-path-separators (list "  ~" "  " "/"))
    (setq dirvish-side-display-alist `((side . right) (slot . -1)))
    (setq dirvish-side-width 40)
    (setq dirvish-subtree-file-viewer 'dired-find-file)
    (setq dirvish-side-auto-close t)
    (map! :map dirvish-mode-map
          :n "h" #'dired-up-directory
          :n "l" #'dired-find-file
          :n "e" #'dired-create-empty-file
          :n "." #'dired-omit-mode
          :n "q" #'dirvish-quit
          :n "s" #'dirvish-quicksort
          :n "a" #'dirvish-quick-access
          :n "F" #'dirvish-fd
          :n "S" #'dirvish-fd-switches-menu
          :n "y" #'dirvish-yank-menu
          :n "f" #'dirvish-file-info-menu
          :n "H" #'dirvish-history-jump
          :n "TAB" #'dirvish-subtree-toggle
          :n [backtab] #'dirvish-subtree-up
          :n "<mouse-1>" #'dirvish-subtree-toggle
          :n "<mouse-2>" #'dirvish-subtree-toggle
          :n "<mouse-3>" #'dired-find-file
          :n "<mouse-8>" #'dired-up-directory
          :n "<mouse-9>" #'dired-find-file
          :n "<double-mouse-1>" #'dired-find-file
          :n "<double-mouse-3>" #'dired-up-directory
          "M-t" #'dirvish-layout-toggle
          "M-j" #'dirvish-fd-jump
          "M-m" #'dirvish-mark-menu )
    )
#+end_src

以及一些相关的常用操作，我将其绑定到SPC-v-...中
#+begin_src emacs-lisp
  (map! :leader
        :desc "Open dired" "N" #'dired-jump
        :desc "Open dirvish" "V" #'dirvish
        (:prefix ("v" . "my personal bindings")
         :desc "Open dirvish" "v" #'dirvish
         :desc "Open Normal Dired" "n" #'dired-jump
         :desc "Quit dirvish" "q" #'dirvish-quit
         :desc "Toggle dirvish-side" "s" #'dirvish-side
         :desc "Fd in dirvish" "F" #'dirvish-fd
         :desc "Jump using fd" "J" #'dirvish-fd-jump
         :desc "Jump recent dir" "j" #'consult-dir
         :desc "Fd find file in dir" "f" #'+vertico/consult-fd
         :desc "find Item in the buffer" "i" #'consult-imenu
         :desc "open with other coding system" "c" #'revert-buffer-with-coding-system
         :desc "change buffer coding system" "C" #'set-buffer-file-coding-system
         :desc "List processes" "l" #'list-processes
         :desc "calc mode" "a" #'literate-calc-mode
         ))
#+end_src

设置关闭window后选择的window。
设置为pos以和dirvish兼容。
不然如eshell-toggle等操作时会选择到预览窗口中去。
#+begin_src emacs-lisp
  (setq delete-window-choose-selected 'pos)
#+end_src

另外，另一个问题：即在dirvish界面打开另一个窗口，
如find-file开个新文件或者开个magit，
新窗口会开在perview的window上，目前还没找到解决办法。

* 终端
emacs里终端我主要用两个，eshell和vterm。
eshell打开就在当前文件目录下，vterm打开会在当前项目目录下。
vterm中运行的是zsh，并且性能较好，所以会更常用些。
#+begin_src emacs-lisp
  (after! vterm
    (setq vterm-max-scrollback 10000)
    (setq vterm-timer-delay 0.01)
    (setq vterm-buffer-name-string "vterm: %s")
    (advice-add #'vterm--redraw :after (lambda (&rest args) (evil-refresh-cursor evil-state)))
    (set-face-attribute 'vterm-color-black nil :background "#a7a7a7")
    )
  (map! :leader
        :desc "open vterm here" "T" #'+vterm/here)
#+end_src

使用vterm-toggle
#+begin_src emacs-lisp
  (use-package! vterm-toggle
    :commands (vterm-toggle)
    :config
    (setq vterm-toggle-reset-window-configration-after-exit nil)
    )

  (map! :map vterm-mode-map [f4] nil)
  (map! [f4] #'vterm-toggle
        :leader
        :desc "toggle vterm" "o t" #'vterm-toggle
        )
#+end_src

* 输入法
** sis
配置中英文输入法自动切换。
#+begin_src emacs-lisp
  (use-package! sis
    :config
    (sis-ism-lazyman-config "1" "2" 'fcitx5)
    ;; enable the /cursor color/ mode
    ;; (sis-global-cursor-color-mode t)
    ;; enable the /respect/ mode
    (sis-global-respect-mode t)
    ;; enable the /context/ mode for all buffers
    (sis-global-context-mode t)
    ;; enable the /inline english/ mode for all buffers
    ;; (sis-global-inline-mode t)
    )
#+end_src

* Org-Mode
** word-wrap
中英文一起时word-wrap只会是副作用。
比如在列表开头给你整一个空行。。
至于为什么用hook，因为直接设置word-wrap nil没有用。
关闭后会导致长代码折行时不好看，但我认为不让列表出现空行更重要。
要看org中的代码自己开！
#+begin_src emacs-lisp
  (add-hook! 'org-mode-hook #'toggle-word-wrap)
#+end_src

** 基本外观
配置一下Org-Mode的主题颜色、字体大小等。
最后一行用于设置org-mode的代码块，使其能有代码缩进，更好看些。
另外做个备忘，org-mode中提升标题等级是M+左箭头，降低是M+右箭头。
#+begin_src emacs-lisp
  (setq org-directory "~/Notes")

  (defun my/org-colors-tomorrow-night ()
    (interactive)
    (dolist
        (face
         '((org-level-1 1.3 "#81a2be" ultra-bold)
           (org-level-2 1.2 "#b294bb" extra-bold)
           (org-level-3 1.1 "#b5bd68" bold)
           (org-level-4 1.0 "#e6c547" semi-bold)
           (org-level-5 1.0 "#cc6666" normal)
           (org-level-6 1.0 "#70c0ba" normal)
           (org-level-7 1.0 "#b77ee0" normal)
           (org-level-8 1.0 "#9ec400" normal)))
      (set-face-attribute (nth 0 face) nil :weight (nth 3 face) :height (nth 1 face) :foreground (nth 2 face)))
    (set-face-attribute 'org-table nil :weight 'normal :height 1.0 :foreground "#bfafdf"))

  (defun my/org-colors-tomorrow-day()
    (interactive)
    (dolist
        (face
         '((org-level-1 1.3 "#4271ae" ultra-bold)
           (org-level-2 1.2 "#8959a8" extra-bold)
           (org-level-3 1.1 "#b5bd68" bold)
           (org-level-4 1.0 "#e6c547" semi-bold)
           (org-level-5 1.0 "#c82829" normal)
           (org-level-6 1.0 "#70c0ba" normal)
           (org-level-7 1.0 "#b77ee0" normal)
           (org-level-8 1.0 "#9ec400" normal)))
      (set-face-attribute (nth 0 face) nil :weight (nth 3 face) :height (nth 1 face) :foreground (nth 2 face)))
    (set-face-attribute 'org-table nil :weight 'normal :height 1.0 :foreground "#bfafdf"))

  (after! org
    (my/org-colors-tomorrow-day)
    (setq org-src-preserve-indentation nil)
    (setq org-image-actual-width 500)
    )
#+end_src

** org-modern
使用org-modern美化org
#+begin_src emacs-lisp
  (use-package! org-modern
    :commands (org-modern-mode)
    :init
    (setq org-modern-block-name nil)
    (setq org-modern-star '("◉" "○" "✸" "✿" "◈" "◇"))
    )

  (add-hook 'org-mode-hook #'org-modern-mode)
#+end_src

** org-appear
#+begin_src emacs-lisp
  (use-package! org-appear
    :commands (org-appear-mode)
    :init
    (setq org-appear-autolinks t)
    )

  (add-hook 'org-mode-hook 'org-appear-mode)
#+end_src

** org-roam
设置笔记文件夹
#+begin_src emacs-lisp
  (setq org-roam-directory "~/Notes/Roam")
  (map! :leader
        :desc "Zettelkasten with org-roam" "v z" #'org-roam-node-find
        :desc "org-roam node Insert" "v i" #'org-roam-node-insert
        )
#+end_src

禁用补全
#+begin_src emacs-lisp
  (after! org-roam
    (setq org-roam-completion-everywhere nil)
    )
#+end_src

日志模板。
主要是使用模板设置保存的文件夹，来兼容我以前的日志模式。
我希望我创建日志的时候能一键弹出，而不用选择模板什么的，所以只设置一个模板。
#+begin_src emacs-lisp
  (setq org-roam-dailies-directory "~/Notes/Daily")
  (setq org-roam-dailies-capture-templates
        '(("d" "default" entry
           "* %?"
           :target (file+head "%<%Y>/%<%Y-%m>/%<%Y-%m-%d>.org"
                              "#+title: %<%Y-%m-%d %A>\n"))))
  (map! :leader
        :desc "my Journal today" "J" #'org-roam-dailies-goto-today
        )
#+end_src

设置模板
同样，也是通过模板来设置保存的文件夹。
org-roam默认将文件堆在一个文件夹下我是不太喜欢的。
#+begin_src emacs-lisp
  (setq org-roam-capture-templates '(
            ("d" "Default" plain "%?"
            :target (file+head "Default/%<%Y%m%d%H%M%S>-${slug}.org"
                                "#+title: ${title}\n#+filetags: \n\n")
            :unnarrowed t)
            ("i" "Inspiration" plain "%?"
            :target (file+head "Inspiration/%<%Y%m%d%H%M%S>-${slug}.org"
                                "#+title: ${title}\n#+filetags: :inspiration: \n\n")
            :unnarrowed t)
            ("l" "Learning" plain "%?"
            :target (file+head "Learning/%<%Y%m%d%H%M%S>-${slug}.org"
                                "#+title: ${title}\n#+filetags: :learning: \n\n")
            :unarrowed t)
            ("r" "Reading" plain "%?"
            :target (file+head "Reading/%<%Y%m%d%H%M%S>-${slug}.org"
                                "#+title: ${title}\n#+filetags: :reading: \n\n")
            :unnarrowed t)
            ("t" "Thinking" plain "%?"
            :target (file+head "Thinking/%<%Y%m%d%H%M%S>-${slug}.org"
                                "#+title: ${title}\n#+filetags: :thinking: \n\n")
            :unnarrowed t)
            ("w" "Working" plain "%?"
            :target (file+head "Working/%<%Y%m%d%H%M%S>-${slug}.org"
                                "#+title: ${title}\n#+filetags: :working: \n\n")
            :unnarrowed t)
            ("v" "Video or VCBs" plain "%?"
            :target (file+head "Video/%<%Y%m%d%H%M%S>-${slug}.org"
                                "#+title: ${title}\n#+filetags: :video: \n\n")
            :unnarrowed t)
            ("p" "Project" plain "%?"
            :target (file+head "Project/%<%Y%m%d%H%M%S>-${slug}.org"
                                "#+title: ${title}\n#+filetags: :project: \n\n")
            :unnarrowed t)
            ("c" "Coding" plain "%?"
            :target (file+head "Coding/%<%Y%m%d%H%M%S>-${slug}.org"
                                "#+title: ${title}\n#+filetags: :coding: \n\n")
            :unnarrowed t)
            ))
#+end_src

设置按键。
我很喜欢Doom给org-capture设置了一个SPC+X的按键。
但我不用org-capture，所以把它重新绑定给org-roam-capture。
这个快捷键很好用很大气。所以我给org-roam的node-find设置为SPC+Z
#+begin_src emacs-lisp
  (map! :leader
        :desc "org-roam capture" "X" #'org-roam-capture
        :desc "org-roam find node" "Z" #'org-roam-node-find
        )
#+end_src

* 常用语言mode
** markdown-mode
也是设置一下字体大小和颜色。
在emacs下我也很少写markdown了。
#+begin_src emacs-lisp
  (custom-set-faces
   '(markdown-header-face ((t (:inherit font-lock-function-name-face :weight bold :family "variable-pitch"))))
   '(markdown-header-face-1 ((t (:inherit markdown-header-face :height 1.3))))
   '(markdown-header-face-2 ((t (:inherit markdown-header-face :height 1.2))))
   '(markdown-header-face-3 ((t (:inherit markdown-header-face :height 1.1))))
   '(markdown-header-face-4 ((t (:inherit markdown-header-face :height 1.0))))
   '(markdown-header-face-5 ((t (:inherit markdown-header-face :height 1.0))))
   '(markdown-header-face-6 ((t (:inherit markdown-header-face :height 1.0)))))
#+end_src

** go-mode
开启lsp的自动import和format。
因为在开启lsp的情况下，go-mode的这部分功能被关闭了，全部交给了gopls。
#+begin_src emacs-lisp
  (defun my/eglot-organize-imports ()
    (call-interactively 'eglot-code-action-organize-imports))
  (defun my/before-saving-go ()
    (add-hook 'before-save-hook #'eglot-format-buffer -10 t)
    (add-hook 'before-save-hook #'my/eglot-organize-imports nil t))
  (add-hook 'go-mode-hook #'my/before-saving-go)
#+end_src

** protobuf-mode
#+begin_src emacs-lisp
  (use-package protobuf-mode
    :commands (protobuf-mode)
    :mode("\\.proto\\'" . protobuf-mode)
    )
#+end_src

** shell
设置shell的formatter
我已经忘了我为什么要设置这个。
似乎是不设置会报错。
#+begin_src emacs-lisp
  (after! sh-script
    (set-formatter! 'shfmt
      '("shfmt" "-ci"
        ("-i" "%d" (unless indent-tabs-mode tab-width))
        ("-ln" "%s" (pcase sh-shell (`bash "bash") (`zsh "bash") (`mksh "mksh") (_ "posix")))))
    )
#+end_src

** .vpy文件
设置用python-mode打开vpy文件
#+begin_src emacs-lisp
  (add-to-list 'auto-mode-alist '("\\.vpy\\'" . python-mode))
#+end_src

* 工具包
** 单词翻译
#+begin_src emacs-lisp
  (use-package! fanyi
    :commands (fanyi-dwim
               fanyi-dwim2)
    :custom
    (fanyi-providers '(;; 海词
                       fanyi-haici-provider
                       ;; 有道同义词词典
                       fanyi-youdao-thesaurus-provider
                       ;; Etymonline
                       ;; fanyi-etymon-provider
                       ;; Longman
                       ;; fanyi-longman-provider
                       )))

  (set-popup-rule! "^\\*fanyi*" :size 0.3 :modeline t :quit t)
  (map! :leader
        :desc "Translate word" "v t" #'fanyi-dwim2
        )
#+end_src

** 窗口布局记录
#+begin_src emacs-lisp
  (use-package! burly
    :commands (burly-bookmark-frames
               burly-bookmark-windows
               burly-open-bookmark
               burly-open-last-bookmark)
    )

  (map! :leader
        :desc "bookmark this window" "v m" #'burly-bookmark-windows
        :desc "bookmark this frame" "v M" #'burly-bookmark-frames
        :desc "bookmark this window" "b w" #'burly-bookmark-windows
        :desc "bookmark this frame" "b f" #'burly-bookmark-frames
        )
#+end_src

** restclient
配置restclient，使之与vscode的restclient兼容。
代码来源：[[https://github.com/yurifrl/restclient/blob/b025b6f87fb85a3e6471e475aca8ffb7005f6163/restclient.el#LL187C1-L201C1][restclient-vscode-compatible]]
#+begin_src emacs-lisp
  (after! restclient
    (setq restclient-use-var-regexp
          "{{\([^{ \n]+\)}}$")
    (setq restclient-var-regexp
          (concat "^\\(@[^@= ]+\\)[ \t]*\\(:?\\)=[ \t]*\\(<<[ \t]*\n\\(\\(.*\n\\)*?\\)" restclient-comment-separator "\\|\\([^<].*\\)$\\)"))
    (setq restclient-svar-regexp
          "^\\(@[^@= ]+\\)[ \t]*=[ \t]*\\(.+?\\)$")
    (setq restclient-evar-regexp
          "^\\(@[^@ ]+\\)[ \t]*:=[ \t]*\\(.+?\\)$")
    (setq restclient-mvar-regexp
          "^\\(@[^@ ]+\\)[ \t]*:?=[ \t]*\\(<<\\)[ \t]*$")
    )
#+end_src
